### ISSUE TITLE
issue for installation

### ISSUE THREAD

**Issue by Tiancaizhi** [cda-tum/mqt-dasqa#1]
I try to install the package, but obtain an error:
~~~
PackagesNotFoundError: The following packages are not available from current channels:

  - environment.yml
![1686876230195](https://github.com/cda-tum/dasqa/assets/81305448/2d96d732-d43d-47ef-bf83-4bd299b3bd8f)

~~~
This is my channel infromation:
~~~
 $conda config --get channels
--add channels 'defaults'   # lowest priority
--add channels 'conda-forge'   # highest priority
~~~
What should I do to fix this? Which channel do I need?

**Comment by jagandecapri** [comment]
Hi there, sorry for the late reply. My research direction changed in the past year. I've updated the readme with hopefully better instruction on setting up. I've tested it locally and it is working for me. Hope it helps.

**Comment by burgholzer** [comment]
Closing this for now, as it is hopefully resolved. Please feel free to reopen if the issue should not be resolved.
