### ISSUE TITLE
the missing csv file

### ISSUE THREAD

**Issue by lzy199905** [cda-tum/mqt-dasqa#2]
hello,  the 'train_statistical_model' file lacks a csv file and cannot be run, could you please update it? Or what is the format of this file?

**Comment by jagandecapri** [comment]
Hi there, sorry for the late reply. My research direction changed. Nevertheless, I've updated the csv file containing the data.

**Comment by burgholzer** [comment]
Closing this for now, as it seems to be resolved. Please feel free to reopen if the issue should not be resolved.
